version: '3.9'

services:
  autobots:
    container_name: autobots
    build:
      context: .
      dockerfile: Dockerfile.local
      args:
        - GITLAB_ACCESS_TOKEN=xwN1zHMzss6-TtBbNEy4
        - ITA_PROJECT_NAME=autobots
    environment:
      - CONFIG_ENVIRONMENT=ec2
    ports:
      - "8080:8080"
      - "8081:8081"
networks:
  default:
    external:
      name: app-net
