service:
  servicename: autobots
  shutdowntimeout: 1ms
  shutdowndelay: 1ms
  http:
    port: 8080
  grpc:
    port: 8081

clients:
  logger:
    level: info
  temporal:
    taskqueueprefix: TASK_QUEUE
    hostport: temporal-fe-dev.service.consul:7233
    clients:
      dummy:
        retention: 1 # days
        worker:
          maxconcurrentactivitytaskpollers: 1
      wish_cash_payment:
        retention: 1 # days
        worker:
          maxconcurrentactivitytaskpollers: 1
