service:
  servicename: autobots
  shutdowntimeout: 1ms
  shutdowndelay: 1ms
  http:
    port: 8080
  grpc:
    port: 8081

clients:
  logger:
    level: info
  temporal:
    taskqueue: TRANSACTION_TASK_QUEUE
    hostport: temporal-fe-dev.service.consul:7233
