service:
  servicename: autobots
  shutdowntimeout: 1ms
  shutdowndelay: 1ms
  http:
    port: 8080
  grpc:
    port: 8081

clients:
  logger:
    level: info
  temporal:
    taskqueueprefix: TASK_QUEUE
    hostport: temporal-fe.service.consul:7233
    clients:
      dummy:
        activities:
          starttoclosetimeout: 1 # minutes
          retrypolicy:
            initialinterval: 1 # seconds
            backoffcoefficient: 1.0
            maximuminterval: 1 # seconds
            maximumattempts: 10
        retention: 1 # days
        worker:
          maxconcurrentactivitytaskpollers: 1
      wish_cash_payment:
        activities:
          starttoclosetimeout: 10 # minutes
          retrypolicy:
            initialinterval: 1 # seconds
            backoffcoefficient: 1.0
            maximuminterval: 1 # seconds
            maximumattempts: 10
        retention: 1 # days
        worker:
          maxconcurrentactivitytaskpollers: 1
  wishfrontend:
    host: wish-frontend.service.consul:10001
    timeout: 30 # seconds
